/**
 * Lettercross - pure rules. NO DOM, NO React, NO Phaser (games/logic-is-pure.test.ts).
 *
 * A crossword tile game. Lay letters on a grid, every run of two or more must
 * be a word, score by letter value and premium square.
 *
 * WHAT IS DELIBERATELY NOT THE GAME YOU ARE THINKING OF, and why it is in the
 * code rather than in a lawyer's note: game MECHANICS are not copyrightable
 * (17 U.S.C. 102(b)), but a clone's overall commercial impression can still be
 * actionable, and the 2008 Scrabulous settlement had its authors change the
 * tiles per turn, at least half the letter values, at least half the letter
 * distribution, the premium-square pattern and the centre star. So:
 *
 *   board        11 x 11, not 15 x 15
 *   rack         8 tiles at the middle level, not 7
 *   values       14 of 26 letters differ (pinned by logic.test.ts)
 *   distribution its own, built from English letter frequency
 *   premiums     a diamond and a ring, generated by a RULE below - no X, no
 *                edge-to-edge diagonals
 *   centre       a plain start square with NO multiplier and no star
 *   wilds        four, not two - twice what the classic gives you
 *
 * See NOTICE.md for the word-list provenance, which is the other half of this.
 */
import { WORDS } from "./words";

export const SIZE = 11;
export const CENTRE = 5 * SIZE + 5;
/** The middle level's rack. `rackFor` is the real answer; this is medium's. */
export const RACK = 8;

export type Level = "easy" | "medium" | "hard";
export type Premium = "none" | "dl" | "tl" | "dw" | "tw";
/** A square: a letter, and whether the tile spelling it was a wild (scores 0). */
export type Cell = { readonly letter: string; readonly wild: boolean } | null;
export type Board = readonly Cell[];
/** A tile in hand. "?" is a wild; it becomes a letter only when placed. */
export type Tile = string;
export type Placement = { readonly index: number; readonly letter: string; readonly wild: boolean };

export type State = {
  readonly level: Level;
  readonly board: Board;
  readonly rack: readonly Tile[];
  readonly bag: readonly Tile[];
  readonly score: number;
  readonly played: number;
};

/**
 * Letter values. Frequency-shaped, and 14 of the 26 differ from the famous
 * board's - `logic.test.ts` pins that count so a later "tidy-up" cannot quietly
 * restore them.
 */
export const LETTER_VALUE: Readonly<Record<string, number>> = {
  a: 1, b: 4, c: 2, d: 2, e: 1, f: 4, g: 3, h: 2, i: 1, j: 9, k: 6, l: 2, m: 4,
  n: 1, o: 1, p: 2, q: 12, r: 1, s: 1, t: 1, u: 2, v: 5, w: 4, x: 9, y: 4, z: 12,
};

const COUNTS: Readonly<Record<string, number>> = {
  e: 10, a: 7, i: 7, o: 7, n: 5, r: 5, t: 5, s: 5, l: 5, u: 4, d: 4, c: 3, h: 3,
  m: 2, g: 2, p: 2, b: 2, y: 2, f: 2, w: 2, v: 1, k: 1, j: 1, x: 1, q: 1, z: 1,
};

/** Four wilds - twice the usual two. A wild scores 0 but spells any letter. */
export const WILDS = 4;

export const BAG: readonly Tile[] = (() => {
  const out: Tile[] = [];
  for (const [ch, n] of Object.entries(COUNTS)) for (let i = 0; i < n; i++) out.push(ch);
  for (let i = 0; i < WILDS; i++) out.push("?");
  return out;
})();
export const TOTAL_TILES = BAG.length;

/** Easy hands you more letters to work with. It never changes the DICTIONARY. */
export function rackFor(level: Level): number {
  return level === "easy" ? 9 : level === "hard" ? 7 : 8;
}

/** The score board a level records against - the scales are not comparable. */
export function bestLevel(level: Level): string {
  return level;
}

/**
 * The premium map, as a RULE rather than a hand-drawn table. Two reasons: a
 * rule is symmetric by construction, so no corner is quietly luckier than
 * another; and a rule is demonstrably our own arrangement rather than a
 * transcription of somebody else's board.
 */
export function premiumAt(index: number): Premium {
  if (index === CENTRE) return "none"; // the start square multiplies nothing
  const dr = Math.abs(Math.floor(index / SIZE) - 5);
  const dc = Math.abs((index % SIZE) - 5);
  if ((dr === 5 && dc === 5) || (dr === 5 && dc === 0) || (dr === 0 && dc === 5)) return "tw";
  if (dr === 4 && dc === 4) return "dw";
  if (dr === 2 && dc === 2) return "tl";
  if (dr + dc === 3) return "dl";
  return "none";
}

function shuffle<T>(xs: readonly T[], rng: () => number): T[] {
  const a = [...xs];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export function newGame(level: Level, rng: () => number = Math.random): State {
  const bag = shuffle(BAG, rng);
  const n = rackFor(level);
  return {
    level,
    board: Array<Cell>(SIZE * SIZE).fill(null),
    rack: bag.slice(0, n),
    bag: bag.slice(n),
    score: 0,
    played: 0,
  };
}

/** Refill a rack from the bag. Returns the new rack and what is left. */
export function draw(rack: readonly Tile[], bag: readonly Tile[], want: number) {
  const need = Math.max(0, want - rack.length);
  return { rack: [...rack, ...bag.slice(0, need)], bag: bag.slice(need) };
}

export type Scored = { readonly word: string; readonly score: number };
export type Verdict =
  | { readonly ok: true; readonly words: readonly Scored[]; readonly total: number }
  | { readonly ok: false; readonly reason: "line" | "gap" | "start" | "touch" | "word" | "empty" };

const rowOf = (i: number) => Math.floor(i / SIZE);
const colOf = (i: number) => i % SIZE;

/** Walk a filled run through `index` along a step, and return it with its cells. */
function runThrough(board: Board, index: number, step: number): number[] {
  const sameLine = (a: number, b: number) =>
    step === 1 ? rowOf(a) === rowOf(b) : colOf(a) === colOf(b);
  let start = index;
  while (start - step >= 0 && sameLine(start, start - step) && board[start - step]) start -= step;
  const run: number[] = [];
  for (let i = start; i < SIZE * SIZE && board[i] && (i === start || sameLine(i, i - step)); i += step) run.push(i);
  return run;
}

export function validate(board: Board, placements: readonly Placement[]): Verdict {
  if (placements.length === 0) return { ok: false, reason: "empty" };
  if (placements.some((p) => board[p.index] !== null)) return { ok: false, reason: "line" };

  const rows = new Set(placements.map((p) => rowOf(p.index)));
  const cols = new Set(placements.map((p) => colOf(p.index)));
  const horizontal = rows.size === 1;
  const vertical = cols.size === 1;
  if (!horizontal && !vertical) return { ok: false, reason: "line" };

  // The merged board: what it would look like if this play stood.
  const next: Cell[] = [...board];
  for (const p of placements) next[p.index] = { letter: p.letter.toLowerCase(), wild: p.wild };

  // Contiguity along the main axis, counting tiles already on the board.
  // Checked BEFORE the start-square rule: two tiles either side of the centre
  // with a hole between them is a gap, and calling that "you missed the start"
  // would send the player to fix the wrong thing.
  const step = horizontal ? 1 : SIZE;
  const idxs = placements.map((p) => p.index).sort((a, b) => a - b);
  for (let i = idxs[0]; i <= idxs[idxs.length - 1]; i += step) if (!next[i]) return { ok: false, reason: "gap" };

  const firstMove = board.every((c) => c === null);
  if (firstMove) {
    if (!placements.some((p) => p.index === CENTRE)) return { ok: false, reason: "start" };
  } else {
    const touches = placements.some((p) => {
      const r = rowOf(p.index), c = colOf(p.index);
      return (
        (r > 0 && board[p.index - SIZE]) || (r < SIZE - 1 && board[p.index + SIZE]) ||
        (c > 0 && board[p.index - 1]) || (c < SIZE - 1 && board[p.index + 1])
      );
    });
    if (!touches) return { ok: false, reason: "touch" };
  }

  const placed = new Set(placements.map((p) => p.index));
  const seen = new Set<string>();
  const words: Scored[] = [];

  const collect = (run: number[]) => {
    if (run.length < 2) return true;
    const key = run.join(",");
    if (seen.has(key)) return true;
    seen.add(key);
    const word = run.map((i) => next[i]!.letter).join("");
    if (!WORDS.has(word)) return false;
    let sum = 0;
    let mult = 1;
    for (const i of run) {
      const cell = next[i]!;
      let v = cell.wild ? 0 : (LETTER_VALUE[cell.letter] ?? 0);
      if (placed.has(i)) {
        const pr = premiumAt(i);
        if (pr === "dl") v *= 2;
        else if (pr === "tl") v *= 3;
        else if (pr === "dw") mult *= 2;
        else if (pr === "tw") mult *= 3;
      }
      sum += v;
    }
    words.push({ word, score: sum * mult });
    return true;
  };

  // The main word along the axis of play, then every cross-word a new tile made.
  if (!collect(runThrough(next, idxs[0], step))) return { ok: false, reason: "word" };
  for (const p of placements) if (!collect(runThrough(next, p.index, step === 1 ? SIZE : 1))) return { ok: false, reason: "word" };

  return { ok: true, words, total: words.reduce((n, w) => n + w.score, 0) };
}

/**
 * Take a turn. Returns a NEW state and never touches the one it was handed -
 * `useGameSession` snapshots this object, and a mutated board would be written
 * to disk under the previous turn's score.
 *
 * Tiles are spent by matching letter, and a wild spends a "?". A placement
 * whose letter is not in the rack spends an arbitrary tile instead of throwing:
 * the renderer only ever builds placements from the rack, and a logic core that
 * can throw mid-turn loses the whole board rather than one illegal move.
 */
export function apply(state: State, placements: readonly Placement[]): State {
  const v = validate(state.board, placements);
  if (!v.ok) return state;

  const board: Cell[] = [...state.board];
  for (const p of placements) board[p.index] = { letter: p.letter.toLowerCase(), wild: p.wild };

  const rack = [...state.rack];
  for (const p of placements) {
    const want = p.wild ? "?" : p.letter.toLowerCase();
    const at = rack.indexOf(want);
    rack.splice(at >= 0 ? at : 0, 1);
  }

  const filled = draw(rack, state.bag, rackFor(state.level));
  return {
    ...state,
    board,
    rack: filled.rack,
    bag: filled.bag,
    score: state.score + v.total,
    played: state.played + 1,
  };
}

/** The run ends when there is nothing left to play with. */
export function isOver(state: State): boolean {
  return state.bag.length === 0 && state.rack.length === 0;
}
