// The Owl King at 64 pixels (boss size): a big brown ovoid with huge yellow eyes, a gold crown, ear tufts, folded wings and orange talons.
//
// Painted 2026-09-06 with the craft rules the knight set (see
// docs/pixel-characters.md): native size by role, clusters not dots, one
// light, hue-shifted ramps, its own selective outline. 56 wide x 64 tall,
// feet on the last row. rig64.ts cuts it into parts.

export const OWL64_W = 56;
export const OWL64_H = 64;

export const OWL64_PALETTE: Record<string, string> = {
  O: "#1a1230",
  F: "#b8783c",
  f: "#dea468",
  d: "#7a4a1e",
  q: "#4a2a0e",
  L: "#f4dfb0",
  l: "#d9b880",
  Y: "#ffe680",
  y: "#ffc21a",
  K: "#1a1a2e",
  W: "#ffffff",
  N: "#ff8c2a",
  n: "#c95e14",
  G: "#ffd23f",
  g: "#c9932a",
};

export const OWL64_GRID: string[] = [
  "............................O...........................",
  "....................O...O..OGO..O...O...................",
  "...................OGO.OGO.OGO.OGO.OGO..................",
  "..........O........OGO.OGO.OGO.OGO.OGO.......O..........",
  ".........OfO.......OGOOOGOOOGOOOGOOOGO......OfO.........",
  "..........OfO......OGGGGGGGGGGGGGGGggO.....OFO..........",
  "..........OffO.....OGGGGGGGGGGGGGGGggO....OFFO..........",
  "..........OfffOO...OGGGGGGGGNGGGGGGggO..OOFFFO..........",
  "...........OffffO..OGGGNGGGGNGGGGNGggO.OFFFFO...........",
  "...........OfffffOOfGGGGGGGGGGGGGGGggOOFFFFFO...........",
  "...........OffffffffgggggggggggggggggFFFFFFFO...........",
  "............OfffffffffffffffffffffffFFFFFFFO............",
  "............OfffffffffffffffffffffFFFFFFFFFO............",
  "............OffffffffffffffffffffFFFFFFFFFFO............",
  "............OffffffffffffffffffFFFFFFFFFFFFO............",
  "............OfffffffffffffffffFFFFFFFFFFFFFO............",
  "............OfffffffffffffffFFFFFFFFFFFFFFFO............",
  "............OffffffffffffffFFFFFFFFFFFFFFFFO............",
  ".............OffffffffffffFFFFFFFFFFFFFFFFO.............",
  ".............OfffWWWWWWfFFFFFFFFFWWWWWWFFFO.............",
  ".............OfWWWYYYYWWWFFFFFFWWWYYYYWWWFO.............",
  ".............OfWYYYYYYYYWFFFFFFWYYYYYYyyWFO.............",
  ".............OWWYYYYYYYYWWFFFFWWYYYYYyyyWWO.............",
  ".............OWYYYYKKYYYYWFFFFWYYYYKKyyyyWO.............",
  ".............OWYYYKWKKYYYWFFFFWYYYKWKKyyyWO.............",
  "............OfWYYKKKKKKYYWFFFFWYYKKKKKKyyWFO............",
  "......OOOO..OfWYYKKKKKKYYWFFFFWYYKKKKKKyyWFO..OOOO......",
  ".....OfFFFO.OFWWYYKKKKYYWWFFFFWWyyKKKKyyWWFO.OFFFFO.....",
  "....OffFFFFOFFFWYYYKKYYYWFFFFFFWyyyKKyyyWFFFOFFFFFdO....",
  "....OffFFFFOFFFWWWYYYYWWWFFFFFFWWWyyyyWWWFFFOFFFFFdO....",
  "...OfffFFFFFFOFFFWWWWWWFFNNNNNNFFWWWWWWFFFOFFFFFFFddO...",
  "...OfffFFFFFFOFFFFFFFFFFLLNNnnnLFFFFFFFFFFOFFFFFFFddO...",
  "...OfffFFFFFFOFFFFFFFFLLLLNNNNLLLLFFFFFFFFOFFFFFFFddO...",
  "..OffffFFFFFFOFFFFFFFLLLLLLNNLLLLLLFFFFFFFOFFFFFFFdddO..",
  "..OffffFFFFFFOFFFFFFLLLLLLLNnLLLLLLlFFFFFFOFFFFFFFdddO..",
  "..OffffFFFFFFOFFFFFLLLLLLLLLLLLLLLLllFFFFFOFFFFFFFdddO..",
  "..OffffFFFFFFOFFFFFlLLLLlLLLLlLLLLlllFFFFFOFFFFFFFdddO..",
  "..OffffFFFFFFOFFFFLLLLLLLLLLLLLLLLLlllFFFFOFdddddddddO..",
  "..OffffFFFFFFOFFFFLLLLLLLLLLLLLLLLLlllFFFFOFdddddddddO..",
  "..OffffFFFFFFOFFFFLLLLLLLLLLLLLLLLLlllFFFFOFdddddddddO..",
  "..OFFFFFFFFFFOFFFLLLLLLLLLLLLLLLLLLllllFFFOFdddddddddO..",
  "..OFFFFFFFFFFOFFFLLlLLLLlLLLLlLLLLlllllFFFOFdddddddddO..",
  "..OFFFFFFFFFFOFFFLLLLLLLLLLLLLLLLLLllllFFFOFdddddddddO..",
  "..OFFFFFFFFFFOFFFLLLLLLLLLLLLLLLLLLllllFFFOFdddddddddO..",
  "..OFFFFFFFFFFOFFFLLLLLLLLLLLLLLLLLLllllFFFOFdddddddddO..",
  "..OddddddddddOFFFLLLLLLLLLLLLLLLLLLllllFFFOFdddddddddO..",
  "..OddddddddddOFFFLLlLLLLlLLLLlLLLLlllllFFFOFqqqqqqqqdO..",
  "...OdddddddddOFFFLLLLLLLLLLLLLLLLLLllllFFdOdqqqqqqqqO...",
  "...OddddddddOOFFFFLLLLLLLLLLLLLLLLLlllFdddOOqqqqqqqqO...",
  "...OddddddddOOFFFFLLLLLLLLLLLLLLLLLlllddddOOqqqqqqqqO...",
  "...OddddddddOOFFFFLLLLLLLLLLLLLLLLLlllddddOOqqqqqqqqO...",
  "....OddddddO.OFFFFFlLLLLlLLLLlLLLLllldddddO.OqqqqqqO....",
  ".....OddddO...OFFFFLLLLLLLLLLLLLLLLllddddO...OqqqqO.....",
  "......OOOO....OFFFFFLLLLLLLLLLLLLLLldddddO....OOOO......",
  "...............OFFFFFlllllllllllllldddddO...............",
  "................OFFFFFlllllllllllldddddO................",
  ".................OFFFFFqllllllllqqqqqqO.................",
  "..................OFFqqqqqqqqqqqqqqqqO..................",
  ".................ONNNNNNqqqqqqqqNNNNNNO.................",
  ".................ONNNNNNqqqqqqqqNNNNNNO.................",
  ".................ONNNNNNOOOOOOOONNNNNNO.................",
  "................ONNNNNNNnO....ONNNNNNNnO................",
  "................ONNNNNNNnO....ONNNNNNNnO................",
  "................ONNnNNnNnO....ONNnNNnNnO................",
];
