// The brawler at 48 pixels (hero size): a boxer - red headband, dark hair, blue singlet, white shorts, one glove down and one thrown forward.
//
// Painted 2026-09-06 with the craft rules the knight set (see
// docs/pixel-characters.md): native size by role, clusters not dots, one
// light, hue-shifted ramps, its own selective outline. 34 wide x 48 tall,
// feet on the last row. rig48.ts cuts it into parts.

export const BRAWLER48_W = 34;
export const BRAWLER48_H = 48;

export const BRAWLER48_PALETTE: Record<string, string> = {
  O: "#1a1230",
  F: "#f0b98a",
  f: "#c78a5a",
  d: "#8f5a36",
  H: "#2a1a0e",
  h: "#4a2e1a",
  R: "#ff4d5e",
  r: "#d81f3a",
  x: "#8f1020",
  B: "#3d6cff",
  b: "#2445b8",
  W: "#f4f4ff",
  w: "#c8cce0",
  K: "#1a1a2e",
  T: "#2a2438",
  t: "#4a4260",
};

export const BRAWLER48_GRID: string[] = [
  "..............OOOO................",
  "...........OOOHHHHOOO.............",
  "..........OHHHHHHHHHHO............",
  ".........OHHhhhhHHHHHHO...........",
  ".........OHHHHHHHHHHHhhO..........",
  ".........OHHHHHHHHHHHhhO..........",
  ".........ORRRRRRRRRRRxxO..........",
  ".........OrrrrrrrrrrrxxO..........",
  ".........OHHFFFFFFFFfhhO..........",
  "..........OFFKKFFFKKfdO...........",
  "..........OFFFFFFFFFfdO...........",
  "..........OFFFFddddFfdO...........",
  "..........OffffffffdfdO...........",
  "...........OOOfffffOOO............",
  "....OOOOOOOOOOfffffOOOOO....OOOOO.",
  "...OFFFffFFbbFFFFFFFbbffO..ORRRRrO",
  "...OFFFffFFFFBBBBBBbFFffOOORRRRrrx",
  "...OFFFffFFbbBBBBBBbbbfFFFFRxRrrrx",
  "...OFFFffFFbbBBBBBBbbbfFFFFRxrrrrx",
  "...OFFFffFFbbBBBBBBbbbfFFFFRxrrrrx",
  "...OfffffFFbbBBBBBBbbbfffffrxrrrrx",
  "...OFFFffFFbbBBBBBBbbbfffffrxrrrrx",
  "...OFFFffFFbbBBBBBBbbbffOOOOxxxxxO",
  "...OFFFffFFbbBBBBBBbbbffO...OOOOO.",
  "...OFFFffFFbbBBBBBBbbbffO.........",
  "...OFFFffFFbbBBBBBBbbbffO.........",
  "...OFRRffFFbbBBBBBBbbbffO.........",
  "..ORRRRrrFFbbBBBBBBbbbffO.........",
  "..ORRRrrrrrrrrrrrrrrrrrrO.........",
  ".ORRRrrrrrWWWWWrxxWwwwwwO.........",
  ".ORRrrrrrrWWWWWrxxWwwwwwO.........",
  "..OrrrrrrWWWWWWrxxWwwwwwO.........",
  "..OxxxxxxWWWWWWrxxWwwwwwO.........",
  "...OOxxOOWWWWWWrxxWwwwwwO.........",
  ".....OO.OWWWWWWrxxWwwwwwO.........",
  "........OFFFFFffOFFFFFffO.........",
  "........OFFFFFffOFFFFFffO.........",
  "........OFFFFFffOFFFFFffO.........",
  "........OFFFFFffOFFFFFffO.........",
  "........OFFFFFffOFFFFFffO.........",
  "........OtttttttOtttttttO.........",
  "........OTTTTTTTOTTTTTTTO.........",
  "........OTTTTTTTOTTTTTTTO.........",
  ".......OTttTTTTTOttTTTTTO.........",
  ".......OTttTTTTTOttTTTTTO.........",
  ".......OTTTTTTTTOTTTTTTTO.........",
  ".......OTTTTTTTTOTTTTTTTO.........",
  ".......OTTTTTTTTOTTTTTTTO.........",
];
