// The golem at 64 pixels (boss size): a stone brute - a small head sunk between huge shoulders, arms like pillars with fists at its sides, glowing cracks, moss.
//
// Painted 2026-09-06 with the craft rules the knight set (see
// docs/pixel-characters.md): native size by role, clusters not dots, one
// light, hue-shifted ramps, its own selective outline. 56 wide x 64 tall,
// feet on the last row. rig64.ts cuts it into parts.

export const GOLEM64_W = 56;
export const GOLEM64_H = 64;

export const GOLEM64_PALETTE: Record<string, string> = {
  O: "#1a1230",
  S: "#b4bccf",
  s: "#848da3",
  d: "#5a6278",
  q: "#3a3f52",
  Q: "#262a3a",
  Y: "#ffc46a",
  y: "#ff7a1a",
  K: "#1a1a2e",
  G: "#6fae4a",
  g: "#4a7d30",
};

export const GOLEM64_GRID: string[] = [
  "........................................................",
  "........................................................",
  "........................................................",
  "...........................OO...........................",
  "..........................OSsO..........................",
  "......................OOOOOssOOOOO......................",
  ".....................OSSSSSSSSSSSsO.....................",
  ".....................OSSSSsssssdddO.....................",
  ".....................OSSSSsssssdddO.....................",
  ".....................OSSYyyssYyyddO.....................",
  ".....................OSSyyyssyyyddO.....................",
  ".....................OSSSSsssssdddO.....................",
  "..........OOOOOOO....OSSqqqqqqqqddO......OOOOO..........",
  ".........OGGGGGGGOOOOOSSSSsssssdddOOOOOOOGGGGGO.........",
  ".........OGGGggggSSSSSSSSSsssssdddsssssssGGgggO.........",
  ".OOOOOOOOOSSgSSSSSSSSSddddddddddddssssssssssssOOOOOOOOO.",
  "OSSssssddOOSSSSSSSSSSSSSSSSSSSSsssssssssssssssOddssddddO",
  "OSSssssddOOSSSSSSSSSSSSSSSSSSSssssssssssssssssOddssddddO",
  "OSSssssddOOSSSSSSSSSSSSSSSSSssssssssssssssssssOddssddddO",
  "OSSssssddOOSSSSSSSSSSSSSSSSsssssssssssssssssssOddssddddO",
  "OSSssssddOOSSSSSSSSSSSSSSSssssssssssssssssssssOddssddddO",
  "OSSssssddOOSSSSSSSSSSSSSSsssqsssssssssssssssssOddssddddO",
  "OSSssssddO.OOSSSSSSSSSSsssssqsssssssssssssOOOOOddssddddO",
  "OSSssssddO..OSSSSSSSSSssssssqsssssssssssssO...OddssddddO",
  "OSSssssddO..OSSSSSSSSsssssssqsssssssssssssO...OddssddddO",
  "OSSssssddO..OSSSSSSSsqqsssssssssssssssssssO...OddssddddO",
  "OSSssssddO..OSSSqqqqqsqsssssssssssssssssssO...OddssddddO",
  "OSSssssddO..OSqqSsssssqsssssssysssssssssqsO...OddssddddO",
  "OqqqqqqqqO..OSSSsssssssqsssssssysssssssqssO...OqqqqqqqqO",
  "OSSssssddO..OSSssssssssqsssssssYyssssssqssO...OddssddddO",
  "OSSssssddO..OssssssssssqssssssssysssssqsssO...OddssddddO",
  "OSSssssddO...OssssssssssqssssssssyssssqssO....OddssddddO",
  "OSSssssddO...OssssssssssqssssssssYsssqsssO....OddssddddO",
  "OSSssssddO...OssssssssssqqqqqqsssysssqssdO....OddssddddO",
  "OSSssssddO...OssssssssssssssssqqyqqqqssddO....OddssddddO",
  "OSSssssddO...OssssssssssssssssssyssssddddO....OddssddddO",
  "OSSssssddO...OssssssssssssssssssyssddddddO....OddssddddO",
  "OSSssssddO...OssssssssssssssssssssdddddddO....OddssddddO",
  "OSSssssddO...OssssssssssssssssssdddddddddO....OddssddddO",
  "OSSssssddO...OssqqqqssssssssssdddddddddddO....OddssddddO",
  "OSSssssddO...OssssssqqqqqqqssddddddddddddO....OddssddddO",
  "SSssssssddO...OssssssssssssqqqqdddddddddO....Oddsssddddd",
  "SSssssssddO...OssssssssssdddddddddddddddO....Oddsssddddd",
  "SSssssssddO...OsssssssssddddddddddddddddO....Oddsssddddd",
  "qqqqqqqqqqO...OsssssssqqqqqqqqqqqqqqqqqqO....Oqqqqqqqqqq",
  "SSsqssqsddO...OsssssqqqqqqqqqqqqqqqqqqqqOO...Oddsqsdqddd",
  "SSsqssqsddO..OSSsssssssdddOOOOSSsssssssdddO..Oddsqsdqddd",
  "SSsqssqsddO..OSSsssssssdddO..OSSsssssssdddO..Oddsqsdqddd",
  "dddqddqdddO..OSSsssssssdddO..OSSsssssssdddO..Odddqddqddd",
  "dddqddqdddO..OSSsssssssdddO..OSSsssssssdddO..Odddqddqddd",
  "dddqddqdddO..OSSsssssssdddO..OSSsssssssdddO..Odddqddqddd",
  "OOOOOOOOOO...OSSsssssssdddO..OSSsssssssdddO...OOOOOOOOOO",
  ".............OqqqqqqqqqqqqO..OqqqqqqqqqqqqO.............",
  ".............OSSsssssssdddO..OSSsssssssdddO.............",
  ".............OSSsssssssdddO..OSSsssssssdddO.............",
  ".............OSSsssssssdddO..OSSsssssssdddO.............",
  ".............OSSsssssssdddO..OSSsssssssdddO.............",
  ".............OSSsssssssdddO..OSSsssssssdddO.............",
  "............OsssddqddddddddOOsssddqddddddddO............",
  "............OdddddqddddddddOOdddddqddddddddO............",
  "............OdddddqddddddddOOdddddqddddddddO............",
  "............OdddddqddddddddOOdddddqddddddddO............",
  "............OqqqqqqqqqqqqqqOOqqqqqqqqqqqqqqO............",
  "............OqqqqqqqqqqqqqqOOqqqqqqqqqqqqqqO............",
];
