// GENERATED by scripts/encode-sfx.mjs - do not edit by hand.
//
// Playback gain per sample, bringing every file to a common peak so a strip
// is a fair comparison and not a loudness contest. Measured from the ENCODED
// file, so it accounts for whatever the encoder did, and stored here rather
// than baked into the audio: a number anyone can retune beats an
// irreversible edit to a recording.
//
// 36 files, 120538 B, mono 48 kHz Opus @ 48 kbps, target -6 dBFS.

export const SAMPLE_GAIN: Record<string, number> = {
  "card-fan-1": 0.6166,
  "card-fan-2": 0.5248,
  "card-place-1": 0.5012,
  "card-place-2": 0.6998,
  "card-place-3": 0.5012,
  "card-place-4": 0.6166,
  "card-shove-1": 0.5623,
  "card-shove-2": 0.5012,
  "card-shove-3": 0.7244,
  "card-shove-4": 0.5012,
  "card-shuffle": 0.6026,
  "card-slide-1": 0.5012,
  "card-slide-2": 0.5188,
  "card-slide-3": 0.5012,
  "card-slide-4": 0.5012,
  "card-slide-5": 0.5623,
  "card-slide-6": 0.6607,
  "chip-lay-1": 0.5012,
  "chip-lay-2": 0.5129,
  "chip-lay-3": 0.5188,
  "chips-collide-1": 0.5248,
  "chips-collide-2": 0.507,
  "chips-collide-3": 0.5012,
  "chips-collide-4": 0.5012,
  "chips-handle-1": 0.5012,
  "chips-handle-2": 0.5012,
  "chips-handle-3": 0.6531,
  "chips-handle-4": 0.5559,
  "chips-handle-5": 0.5012,
  "chips-handle-6": 0.537,
  "chips-stack-1": 0.5309,
  "chips-stack-2": 0.5012,
  "chips-stack-3": 0.5188,
  "chips-stack-4": 0.5012,
  "chips-stack-5": 0.7244,
  "chips-stack-6": 0.7586,
};
