// The wizard at 48 pixels (hero size): a purple robe that flares to the boots, a tall pointed hat with a star, a white beard, a staff with a glowing orb.
//
// Painted 2026-09-06 with the craft rules the knight set (see
// docs/pixel-characters.md): native size by role, clusters not dots, one
// light, hue-shifted ramps, its own selective outline. 34 wide x 48 tall,
// feet on the last row. rig48.ts cuts it into parts.

export const WIZARD48_W = 34;
export const WIZARD48_H = 48;

export const WIZARD48_PALETTE: Record<string, string> = {
  O: "#1a1230",
  P: "#a684ff",
  p: "#7452d6",
  q: "#4a2f8f",
  Q: "#2c1a5c",
  Y: "#ffe680",
  W: "#ffffff",
  w: "#cfd3ea",
  F: "#ffd9b3",
  f: "#d9a87a",
  K: "#1a1a2e",
  T: "#8b5a2b",
  t: "#5c3a18",
  S: "#9af0ff",
  s: "#2bb0e0",
  G: "#ffd23f",
};

export const WIZARD48_GRID: string[] = [
  "................OO................",
  "...............OppO...............",
  "..............OppppO........OOOO..",
  "..............OppppO.......OssssO.",
  ".............OPpppppO.....OsSSSssO",
  "............OPPppppppO....OSSWSSsO",
  "............OPPppppYpO....OSSSSSsO",
  "...........OPPPppYYYYYO...OsSSSssO",
  "..........OPPPPppppYpqqO..OssssssO",
  "..........OPPPPppppppqqO...OssssO.",
  ".........OPPPPPppppppqqqO...OttO..",
  "......OOOPPPPPPppppppqqqqOOOOTtO..",
  ".....OPPPPPPPPPppppppqqqqqqqOTtO..",
  ".....OqqqqqqqqqqqqqqqqqqqqqqOTtO..",
  "......OOOOOOffffffffffOOOOOOOTtO..",
  "...........OFWWWFFWWWfO.....OTtO..",
  "...........OFFKKFFKKffO.....OTtO..",
  "...........OFFKKFFKKffO.....OTtO..",
  "...........OFFFFffFFffO.....OTtO..",
  "..........OWWWWWWWwwwwO.....OTtO..",
  "......OOOOOPpppppppqqqO.....OTtO..",
  ".....OPppppPpppppppqqqOOOOOOOTtO..",
  ".....OPppppPpppppppqqqqPPPPPOTtO..",
  ".....OPppppPpppppppqqqqpppppOTtO..",
  ".....OPppppPPpppppppqqqppppqOTtO..",
  ".....OPppppPPpppppppqqqppppqOTtO..",
  "....OqqqqqqPPpppppppqqqppppqOTtO..",
  ".....OPppppPPpppppppqqqpppFFFFO...",
  ".....OPppppPPpppppppqqqpppFFFFO...",
  ".....OPppppPPpppppppqqqpppFFFFO...",
  ".....OPppppGGGGGGGGGGGqpppFFFFO...",
  ".....OPppppGGGGGGGGGGGTqOOOOOTtO..",
  ".....OPFFffPPPpppppppqqqQO..OTtO..",
  ".....OPFFffPPPpppppppqqqQO..OTtO..",
  "......OFFffPPPpppppppqqqqO..OTtO..",
  "......OFFffPPPpppppppqqqqO..OTtO..",
  ".......OPPPPPPpppppppqqqqO..OTtO..",
  "......OPPPPPPPPpppppppqqqQO.OTtO..",
  "......OPPPPPPPPpppppppqqqQO.OTtO..",
  "......OPPPPPPPPpppppppqqqQO.OTtO..",
  "......OPPPPPPPPpppppppqqqqO.OTtO..",
  "......OPPPPPPPPpppppppqqqqO.OTtO..",
  ".....OPPPPPPPPPpppppppqqqqQOOTtO..",
  ".....OPPPPPPPPPpppppppqqqqQO.OO...",
  "......OOOTTttttOOOOTTttttOO.......",
  "........OttttttO..OttttttO........",
  "........OttttttO..OttttttO........",
  "........OttttttO..OttttttO........",
];
