// The robot at 48 pixels (hero size): boxy red shell lit from the upper-left, antenna bulb, yellow visor with two dark eyes, a chest light, one arm hanging and one thrown forward to punch.
//
// Painted 2026-09-05 with the craft rules the knight set (see
// docs/pixel-characters.md): native size by role, clusters not dots, one
// light, hue-shifted ramps, its own selective outline. 36 wide x 48 tall,
// feet on the last row. rig48.ts cuts it into parts.

export const ROBOT48_W = 36;
export const ROBOT48_H = 48;

export const ROBOT48_PALETTE: Record<string, string> = {
  O: "#1a1230",
  R: "#f06a5a",
  r: "#d8342e",
  d: "#8f1c18",
  q: "#5e1210",
  M: "#c9d0dc",
  m: "#9aa3b2",
  n: "#5f6878",
  Y: "#ffe680",
  y: "#ffd23f",
  h: "#c9932a",
  K: "#1a1a2e",
  B: "#5e86ff",
  b: "#2b5cff",
  T: "#2a2438",
  t: "#4a4260",
};

export const ROBOT48_GRID: string[] = [
  "................OOO.................",
  "...............OYYyO................",
  "...............OYyhO................",
  "...............OyhhO................",
  "................OmO.................",
  "................OmO.................",
  "..........OOOOOOOOOOOOOOO...........",
  ".........ORRRRRRRRRRRRRddO..........",
  ".........ORRRRrrrrrrrrdddO..........",
  ".........OROOOOOOOOOOOOOdO..........",
  ".........OROYYYyyyyyyyhOdO..........",
  ".........OROYyyyyyyyyyhOdO..........",
  ".........OROyyKKyyyKKyhOdO..........",
  ".........OROyyKKyyyKKyhOdO..........",
  ".........OROyyyyyyyyyyhOdO..........",
  ".........OROhhhhhhhhhhhOdO..........",
  ".........OROOOOOOOOOOOOOdO..........",
  ".........ORRRRrrrrrrrrdddO..........",
  ".........ORRRRnnnnnnnrdddO..........",
  ".........ORRRRnmnmnmnrdddO..........",
  ".........OdddddddddddddddO......OO..",
  "....OOOOO.OOOOmmmmmmnOOOO.OOOO.OmmO.",
  "...OMMMMmORRRRRRRRRRRRdddOMMMnOmMMmO",
  "...OmmmmmORRRrrrrrrrrrdddOmmmmmmMMnO",
  "...OmmmmnORRRrrrrrrrrrdddOmmmmmmMmnO",
  "....OOOOOORRROOOOOOOOOdddOmmmmmmmmnO",
  ".....OMmnORRROBBBbbbbOdddOOOOnnmmnnO",
  ".....OMmnORRROBBBbbbbOdddO...OOmnnnO",
  ".....OMmnORRROBbbbbbbOdddO.....OmmO.",
  ".....OMmnORRRObbbbbbbOdddO......OO..",
  ".....OMmnORRRObbbbbbbOdddO..........",
  "....OOOOOORRRObbbbbbbOdddO..........",
  "...OMMmmnORRROOOOOOOOOdddO..........",
  "...OMMmmnORRRrrrrrrrrrdddO..........",
  "...OmmmmnOdddddddddddddddO..........",
  "...OnnnnnOqqqqqqqqqqqqqqqO..........",
  "....OOOOO.OqqqqqqqqqqqqqO...........",
  "...........OOOOOOOOOOOOO............",
  "..........OrrdqO...OrrdqO...........",
  "..........OrrdqO...OrrdqO...........",
  "..........OrrdqO...OrrdqO...........",
  "..........OrrdqO...OrrdqO...........",
  "..........OrrdqO...OrrdqO...........",
  ".........OOrrdqO...OrrdqOO..........",
  "........OtttTTTTO.OtttTTTTO.........",
  "........OTTTTTTTO.OTTTTTTTO.........",
  "........OTTTTTTTO.OTTTTTTTO.........",
  ".........OOOOOOO...OOOOOOO..........",
];
